#include "tokens.h"

#define CASE(id, s) case id: return s;

char *get_token_name(int tk_id) {
    switch (tk_id) {
        CASE(TK_K_AUTO, "keyword \"auto\"")
        CASE(TK_K_DOUBLE, "keyword \"double\"")
        CASE(TK_K_INT, "keyword \"int\"")
        CASE(TK_K_STRUCT, "keyword \"struct\"")
        CASE(TK_K_BREAK, "keyword \"break\"")
        CASE(TK_K_ELSE, "keyword \"else\"")
        CASE(TK_K_LONG, "keyword \"long\"")
        CASE(TK_K_SWITCH, "keyword \"switch\"")
        CASE(TK_K_CASE, "keyword \"case\"")
        CASE(TK_K_ENUM, "keyword \"enum\"")
        CASE(TK_K_REGISTER, "keyword \"register\"")
        CASE(TK_K_TYPEDEF, "keyword \"typedef\"")
        CASE(TK_K_CHAR, "keyword \"char\"")
        CASE(TK_K_EXTERN, "keyword \"extern\"")
        CASE(TK_K_RETURN, "keyword \"return\"")
        CASE(TK_K_UNION, "keyword \"union\"")
        CASE(TK_K_CONST, "keyword \"const\"")
        CASE(TK_K_FLOAT, "keyword \"float\"")
        CASE(TK_K_SHORT, "keyword \"short\"")
        CASE(TK_K_UNSIGNED, "keyword \"unsigned\"")
        CASE(TK_K_CONTINUE, "keyword \"continue\"")
        CASE(TK_K_FOR, "keyword \"for\"")
        CASE(TK_K_SIGNED, "keyword \"signed\"")
        CASE(TK_K_VOID, "keyword \"void\"")
        CASE(TK_K_DEFAULT, "keyword \"default\"")
        CASE(TK_K_GOTO, "keyword \"goto\"")
        CASE(TK_K_SIZEOF, "keyword \"sizeof\"")
        CASE(TK_K_VOLATILE, "keyword \"volatile\"")
        CASE(TK_K_DO, "keyword \"do\"")
        CASE(TK_K_IF, "keyword \"if\"")
        CASE(TK_K_STATIC, "keyword \"static\"")
        CASE(TK_K_WHILE, "keyword \"while\"")
        CASE(TK_SEMICOLON, "semicolon")
        CASE(TK_O_CBRAK, "opening curly bracket")
        CASE(TK_C_CBRAK, "closing curly bracket")
        CASE(TK_COMMA, "comma")
        CASE(TK_EQ, "equals")
        CASE(TK_COLON, "colon")
        CASE(TK_O_PAREN, "opening parenthesis")
        CASE(TK_C_PAREN, "closing parenthesis")
        CASE(TK_O_BRAK, "opening bracket")
        CASE(TK_C_BRAK, "closing bracket")
        CASE(TK_STAR, "asterisk")
        CASE(TK_TRIP_DOT, "ellipsis")
        CASE(TK_QMARK, "question mark")
        CASE(TK_ASIGN_STAR, "multiply-equals")
        CASE(TK_ASIGN_SLASH, "divide-equals")
        CASE(TK_ASIGN_MOD, "modulus-equals")
        CASE(TK_ASIGN_PLUS, "plus-equals")
        CASE(TK_ASIGN_MINUS, "minus-equals")
        CASE(TK_ASIGN_SHL, "shift-left-equals")
        CASE(TK_ASIGN_SHR, "shift-right-equals")
        CASE(TK_ASIGN_AND, "and-equals")
        CASE(TK_ASIGN_XOR, "xor-equals")
        CASE(TK_ASIGN_OR, "or-equals")
        CASE(TK_LOGIC_OR, "logical or")
        CASE(TK_LOGIC_AND, "logical and")
        CASE(TK_OR, "bitwise or")
        CASE(TK_XOR, "xor")
        CASE(TK_AND, "bitwise and")
        CASE(TK_EQEQ, "double-equals")
        CASE(TK_NEQ, "not-equals")
        CASE(TK_LT, "less-than")
        CASE(TK_GT, "greater-than")
        CASE(TK_LTE, "less-than-equals")
        CASE(TK_GTE, "greater-than-equals")
        CASE(TK_SHL, "shift left")
        CASE(TK_SHR, "shift right")
        CASE(TK_PLUS, "plus")
        CASE(TK_MINUS, "minus")
        CASE(TK_SLASH, "slash")
        CASE(TK_MOD, "modulus")
        CASE(TK_INC, "increment")
        CASE(TK_DEC, "decrement")
        CASE(TK_TILDA, "tilda")
        CASE(TK_EXCLA, "exclamation mark")
        CASE(TK_DOT, "dot")
        CASE(TK_INDIR_AC, "access arrow")
        CASE(TK_INT_CONST, "integer constant")
        CASE(TK_CHAR_CONST, "character constant")
        CASE(TK_FLOAT_CONST, "floating point constant")
        CASE(TK_IDENT, "identifier")
        CASE(TK_STRING, "string literal")
        CASE(TK_ENUM_CONST, "enum constant")
        CASE(TK_TYPEDEF_NAME, "typedef name")
        default: return "ERR INVAL TOKEN";
    }
}
